### ISSUE TITLE
buildplan report includes color escape sequences

### ISSUE THREAD

**Issue by nyg** [mojohaus/buildplan-maven-plugin#157]
Following #155 (I think), the buildplan report generated when running `mvn site` includes ANSI escape sequences that should be destined for console output only, see below:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/784863/210653990-4fc8ad4e-9dee-42b9-a058-6bfde08b671a.png">

EDIT: Screenshot above was generated with maven-site-plugin 4.0.0-M3. With M4 the output is completely broken:

![image](https://user-images.githubusercontent.com/784863/211042645-b72ffeee-9428-47b0-be6f-8a30e607c2fd.png)

**Comment by jcgay** [comment]
Thanks for the report!

**Comment by nyg** [comment]
@jcgay Thanks for the quick fix and release! I don't know if you noticed but there is a second issue in my screenshot: it seems the the HTML markup is not written to the sink. Should I open another issue?

**Comment by jcgay** [comment]
I've missed it 😇
Don't bother creating a new one I'm doing it!
