### ISSUE TITLE
HTML broken with version 4.0.0-M4 of maven-site-plugin

### ISSUE THREAD

**Issue by jcgay** [mojohaus/buildplan-maven-plugin#163]
It seems the the HTML markup is not written to the sink (happens with version 4.0.0-M4 of maven-site-plugin)

![](https://user-images.githubusercontent.com/784863/211042645-b72ffeee-9428-47b0-be6f-8a30e607c2fd.png)

Reported by @nyg in #157

**Comment by nyg** [comment]
I think it's related to: https://issues.apache.org/jira/browse/MPIR-427
Also see: https://cwiki.apache.org/confluence/display/MAVEN/Towards+Doxia+2.0.0+Stack

> Reporting Plugin Maintainers:
> * **Sink tables must start with Sink#table() + Sink#tableRows() and end with Sink#tableRows_() + Sink#table_()**
> * Runs UTs and ITs and compare HTML output with Doxia 1.x stack. If anything breaks for you, report with us.
> * Anchors must be placed before the target element
